# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  languageCode: ko-kr
  contentDir: content/ko

en:
  languageCode: en-us
  contentDir: content/en
  title: Sangwook You
  params:
    description: Portfolio
  menu:
    main:
      - name: Home
        url: /
        weight: 10
      - name: About
        url: about/
        weight: 20
      - name: Activity
        weight: 30
      - parent: Activity
        name: Project
        url: project/
        weight: 1
      - parent: Activity
        name: Extracurricular Activities
        url: activity/
        weight: 2
# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
